version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:6.6.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: unless-stopped
  manager:
    image: linksmart/deployment-manager
    depends_on:
      - elasticsearch
    environment:
      - STORAGE_DSN=http://elasticsearch:9200
    volumes:
      - ./volumes/keys:/home/keys
    ports:
      - 8080:8080
      - 5556-5557:5556-5557
    restart: unless-stopped
  ui:
    image: linksmart/deployment-ui
    depends_on:
      - manager
    ports:
      - 8090:80
    restart: unless-stopped