openapi: 3.0.0

info:
  description: The API of Deployment Tool (Manager)
  version: "0.5.0"
  title: Deployment Tool REST API
  contact:
    name: Source Code
    url: https://github.com/cpswarm/deployment-tool
  license:
    name: Apache 2.0
    url: 'https://github.com/cpswarm/deployment-tool/blob/master/LICENSE'
tags:
  - name: orders
    description: Managing deployment orders
  - name: targets
    description: Managing targets
paths:
  /orders:
    post:
      tags:
        - orders
      summary: adds an order
      requestBody:
        description: Order to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: 'invalid input, object invalid'
    get:
      tags:
        - orders
      summary: retrieves list of orders
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/Order'
  /orders/{id}:
    parameters:
      - in: path
        name: id
        description: id of the task
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - orders
      summary: retrieves an order
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: not found
  /targets:
    get:
      tags:
        - targets
      summary: retrieves list of targets
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/Target'
  #    post:
  /targets/{id}:
    parameters:
      - in: path
        name: id
        description: id of the target
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - targets
      summary: retrieves a target
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Target'
        '404':
          description: not found
#    put:
components:
  schemas:
    Order:
      title: Order
      type: object
      required:
        - stages
        - target
      properties:
        id:
          type: string
          readOnly: true
        source:
          type: object
          description: Source files
          properties:
            zip:
              description: Base64 encoded zip of artifacts
              type: string
            order:
              description: Copy artifacts from a previous order
              type: string
            paths:
              description: Copy from a local directory on the server (for internal use)
              type: array
              items:
                type: string
        build:
          description: Build stages
          type: object
          properties:
            host:
              description: ID of the target hosting the build
              type: string
            commands:
              description: build shell commands
              type: array
              items:
                type: string
                example: "go build app"
            artifacts:
              description: list of paths to files and directories copied to manager after the build
              type: array
              items:
                type: string
                example: "app"
        deploy:
          description: Deployment stages
          type: object
          properties:
            install:
              type: object
              properties:
                commands:
                  description: installation commands executed sequentially on target devices
                  type: array
                  items:
                    type: string
                    example: "chmod +x app"
            launch:
              type: object
              properties:
                commands:
                  description: commands for executing the applications on target devices
                  type: array
                  items:
                    type: string
                    example: "./app"
            target:
              description: Which target devices should receive the package
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                tags:
                  type: array
                  items:
                    type: string
                    example: [raspi3, gateway]
        debug:
          description: Whether the device should send all standard output (true) or just status info
          type: boolean
          default: false
        created:
          type: integer
          format: int64
          readOnly: true
        childOrder:
          description: The ID of child order generated for deployment of packages
          type: string
          readOnly: true

    Target:
      title: Target
      type: object
      properties:
        tags:
          type: array
          items:
            type: string
        logs:
          type: object
          additionalProperties:
            type: object
            properties:
              transfer:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/stageLog'
              install:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/stageLog'
              run:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/stageLog'
              updated:
                type: integer
                format: int64
                readOnly: true
    stageLog:
      title: Stage Log
      type: object
      properties:
        time:
          type: integer
          format: int64
        output:
          type: string
        error:
          type: boolean
          default: false