version: '2.4'

services:
  device_0:
    image: linksmart/deployment-agent
    container_name: device_0
    labels:
      - virtual_device
    environment:
      ID: device_0
      TAGS: amd64,virtual
      LOCATION_LAT: '7.203973'
      LOCATION_LON: '50.749548'
      AUTH_TOKEN: <token>
      MANAGER_ADDR: http://manager:8080
    volumes:
      - ./volumes/agent_0:/home/agent
    restart: unless-stopped
    command:
      - --fresh
  device_1:
    image: linksmart/deployment-agent
    container_name: device_1
    labels:
      - virtual_device
    environment:
      ID: device_1
      TAGS: amd64,virtual
      LOCATION_LAT: '7.203973'
      LOCATION_LON: '50.749548'
      AUTH_TOKEN: <token>
      MANAGER_ADDR: http://manager:8080
    volumes:
      - ./volumes/agent_1:/home/agent
    restart: unless-stopped
    command:
      - --fresh
  device_2:
    image: linksmart/deployment-agent
    container_name: device_2
    labels:
      - virtual_device
    environment:
      ID: device_2
      TAGS: amd64,virtual
      LOCATION_LAT: '7.203973'
      LOCATION_LON: '50.749548'
      AUTH_TOKEN: <token>
      MANAGER_ADDR: http://manager:8080
    volumes:
      - ./volumes/agent_2:/home/agent
    restart: unless-stopped
    command:
      - --fresh

networks:
  default:
    external:
      name: dt_default